version: '3'

services:
  rmexpired:
    build: .
    deploy:
      restart_policy:
        condition: "on-failure"
    command: ["node", "/opt/eosio/bin/rmexpired.js"]

  sendtokens:
    build: .
    deploy:
      restart_policy:
        condition: "on-failure"
    command: ["node", "/opt/eosio/bin/sendtokens.js"]
