version: '3'

services:
  rmexpired:
    build: .
    restart: on-failure
    command: ["node", "/opt/eosio/bin/rmexpired.js"]
    environment:
      - EOS_NET=testnet
    volumes:
      - ./scripts/config.json:/opt/eosio/bin/config.json

  sendtokens:
    build: .
    restart: on-failure
    command: ["node", "/opt/eosio/bin/sendtokens.js"]
    environment:
      - EOS_NET=testnet
    volumes:
      - ./scripts/config.json:/opt/eosio/bin/config.json

  forcesched:
    build: .
    restart: on-failure
    command: ["node", "/opt/eosio/bin/forcesched.js"]
    environment:
      - EOS_NET=testnet
    volumes:
      - ./scripts/config.json:/opt/eosio/bin/config.json

  rmexpiredmain:
    build: .
    restart: on-failure
    command: ["node", "/opt/eosio/bin/rmexpired.js"]
    environment:
      - EOS_NET=mainet
    volumes:
      - ./scripts/config.json:/opt/eosio/bin/config.json

  sendtokensmain:
    build: .
    restart: on-failure
    command: ["node", "/opt/eosio/bin/sendtokens.js"]
    environment:
      - EOS_NET=mainet
    volumes:
      - ./scripts/config.json:/opt/eosio/bin/config.json

  forceschedmain:
    build: .
    restart: on-failure
    command: ["node", "/opt/eosio/bin/forcesched.js"]
    environment:
      - EOS_NET=mainet
    volumes:
      - ./scripts/config.json:/opt/eosio/bin/config.json
